version: '2'


services:


#########################################################
####                   SECTF 2017                    ####
#########################################################

  traefik:
   image: traefik
   command: --web --docker --docker.domain=se-exe.org --logLevel=DEBUG
   ports:
    - "80:80"
    - "8080:8080"
   volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /dev/null:/traefik.toml
   labels:
    - "traefik.enable=false"


  # Spins up a Jenkins Instance to build code
  web:
    image: tiangolo/uwsgi-nginx-flask:flask-index
    ports:
      - 80
    restart: always
    volumes:
      - ./app:/app:rw
    labels:
      - "container_group=www"
      - "traefik.enable=true"
      - "traefik.backend=web"
      - "traefik.frontend.rule=Host:www.se-exe.org"
      - "traefik.port=80"


#########################################################

  # Data pr0n
  elk:
  image: sebp/elk
  ports:
    - "5601:5601"
    - "9200:9200"
    - "5044:5044"
  environment:
    - "ES_HEAP_SIZE=2g"
    - "LS_HEAP_SIZE=1g"
  labels:
    - "container_group=data"
    - "traefik.enable=true"
    - "traefik.backend=elk"
    - "traefik.frontend.rule=Host:cc.se-exe.org"
    - "traefik.port=80"
